// 66 卷書的 USFM 代碼（跟 YouVersion 格式相容、也是 entry.reference 用的格式，
// 例如 "NEH.2.11-20"）對應到 FHL 查詢用的和合本簡稱、中文全名、章數（給選
// 章節的畫面用，畫出 1..chapters 的格子）。按正典順序排列，也是 Bolls
// 那邊書卷編號（1-66）的順序依據，見 lib/bible/bolls.ts。
export const BIBLE_BOOKS: { code: string; abbr: string; fullName: string; chapters: number }[] = [
  { code: "GEN", abbr: "創", fullName: "創世記", chapters: 50 },
  { code: "EXO", abbr: "出", fullName: "出埃及記", chapters: 40 },
  { code: "LEV", abbr: "利", fullName: "利未記", chapters: 27 },
  { code: "NUM", abbr: "民", fullName: "民數記", chapters: 36 },
  { code: "DEU", abbr: "申", fullName: "申命記", chapters: 34 },
  { code: "JOS", abbr: "書", fullName: "約書亞記", chapters: 24 },
  { code: "JDG", abbr: "士", fullName: "士師記", chapters: 21 },
  { code: "RUT", abbr: "得", fullName: "路得記", chapters: 4 },
  { code: "1SA", abbr: "撒上", fullName: "撒母耳記上", chapters: 31 },
  { code: "2SA", abbr: "撒下", fullName: "撒母耳記下", chapters: 24 },
  { code: "1KI", abbr: "王上", fullName: "列王紀上", chapters: 22 },
  { code: "2KI", abbr: "王下", fullName: "列王紀下", chapters: 25 },
  { code: "1CH", abbr: "代上", fullName: "歷代志上", chapters: 29 },
  { code: "2CH", abbr: "代下", fullName: "歷代志下", chapters: 36 },
  { code: "EZR", abbr: "拉", fullName: "以斯拉記", chapters: 10 },
  { code: "NEH", abbr: "尼", fullName: "尼希米記", chapters: 13 },
  { code: "EST", abbr: "斯", fullName: "以斯帖記", chapters: 10 },
  { code: "JOB", abbr: "伯", fullName: "約伯記", chapters: 42 },
  { code: "PSA", abbr: "詩", fullName: "詩篇", chapters: 150 },
  { code: "PRO", abbr: "箴", fullName: "箴言", chapters: 31 },
  { code: "ECC", abbr: "傳", fullName: "傳道書", chapters: 12 },
  { code: "SNG", abbr: "歌", fullName: "雅歌", chapters: 8 },
  { code: "ISA", abbr: "賽", fullName: "以賽亞書", chapters: 66 },
  { code: "JER", abbr: "耶", fullName: "耶利米書", chapters: 52 },
  { code: "LAM", abbr: "哀", fullName: "耶利米哀歌", chapters: 5 },
  { code: "EZK", abbr: "結", fullName: "以西結書", chapters: 48 },
  { code: "DAN", abbr: "但", fullName: "但以理書", chapters: 12 },
  { code: "HOS", abbr: "何", fullName: "何西阿書", chapters: 14 },
  { code: "JOL", abbr: "珥", fullName: "約珥書", chapters: 3 },
  { code: "AMO", abbr: "摩", fullName: "阿摩司書", chapters: 9 },
  { code: "OBA", abbr: "俄", fullName: "俄巴底亞書", chapters: 1 },
  { code: "JON", abbr: "拿", fullName: "約拿書", chapters: 4 },
  { code: "MIC", abbr: "彌", fullName: "彌迦書", chapters: 7 },
  { code: "NAM", abbr: "鴻", fullName: "那鴻書", chapters: 3 },
  { code: "HAB", abbr: "哈", fullName: "哈巴谷書", chapters: 3 },
  { code: "ZEP", abbr: "番", fullName: "西番雅書", chapters: 3 },
  { code: "HAG", abbr: "該", fullName: "哈該書", chapters: 2 },
  { code: "ZEC", abbr: "亞", fullName: "撒迦利亞書", chapters: 14 },
  { code: "MAL", abbr: "瑪", fullName: "瑪拉基書", chapters: 4 },
  { code: "MAT", abbr: "太", fullName: "馬太福音", chapters: 28 },
  { code: "MRK", abbr: "可", fullName: "馬可福音", chapters: 16 },
  { code: "LUK", abbr: "路", fullName: "路加福音", chapters: 24 },
  { code: "JHN", abbr: "約", fullName: "約翰福音", chapters: 21 },
  { code: "ACT", abbr: "徒", fullName: "使徒行傳", chapters: 28 },
  { code: "ROM", abbr: "羅", fullName: "羅馬書", chapters: 16 },
  { code: "1CO", abbr: "林前", fullName: "哥林多前書", chapters: 16 },
  { code: "2CO", abbr: "林後", fullName: "哥林多後書", chapters: 13 },
  { code: "GAL", abbr: "加", fullName: "加拉太書", chapters: 6 },
  { code: "EPH", abbr: "弗", fullName: "以弗所書", chapters: 6 },
  { code: "PHP", abbr: "腓", fullName: "腓立比書", chapters: 4 },
  { code: "COL", abbr: "西", fullName: "歌羅西書", chapters: 4 },
  { code: "1TH", abbr: "帖前", fullName: "帖撒羅尼迦前書", chapters: 5 },
  { code: "2TH", abbr: "帖後", fullName: "帖撒羅尼迦後書", chapters: 3 },
  { code: "1TI", abbr: "提前", fullName: "提摩太前書", chapters: 6 },
  { code: "2TI", abbr: "提後", fullName: "提摩太後書", chapters: 4 },
  { code: "TIT", abbr: "多", fullName: "提多書", chapters: 3 },
  { code: "PHM", abbr: "門", fullName: "腓利門書", chapters: 1 },
  { code: "HEB", abbr: "來", fullName: "希伯來書", chapters: 13 },
  { code: "JAS", abbr: "雅", fullName: "雅各書", chapters: 5 },
  { code: "1PE", abbr: "彼前", fullName: "彼得前書", chapters: 5 },
  { code: "2PE", abbr: "彼後", fullName: "彼得後書", chapters: 3 },
  { code: "1JN", abbr: "約一", fullName: "約翰一書", chapters: 5 },
  { code: "2JN", abbr: "約二", fullName: "約翰二書", chapters: 1 },
  { code: "3JN", abbr: "約三", fullName: "約翰三書", chapters: 1 },
  { code: "JUD", abbr: "猶", fullName: "猶大書", chapters: 1 },
  { code: "REV", abbr: "啟", fullName: "啟示錄", chapters: 22 },
]

export const BOOK_BY_CODE = new Map(BIBLE_BOOKS.map((b) => [b.code, b]))
